
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 * @version 1.0
 * @author danielortizarenas@gamil.com
 */
public class seguroFrame extends javax.swing.JFrame {

    /**
     * Creates new form seguroFrame
     */
    
    seguroVida calcular = new seguroVida();
    boolean fumador =false, alcholico = false, drogadicto = false, cardiaco = false;
    long valorBase = 0;
    
    public seguroFrame() {
        initComponents();
        setLocationRelativeTo(null);
        textvalorbase.setText("");
        labelfinal.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rgfumadores = new javax.swing.ButtonGroup();
        rgalcoholico = new javax.swing.ButtonGroup();
        rgalucinogena = new javax.swing.ButtonGroup();
        rgcardiacos = new javax.swing.ButtonGroup();
        textvalorbase = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        rbfumadorsi = new javax.swing.JRadioButton();
        rbalcoholno = new javax.swing.JRadioButton();
        rbfumadorno = new javax.swing.JRadioButton();
        rbalucinogenasno = new javax.swing.JRadioButton();
        rbalcoholsi = new javax.swing.JRadioButton();
        rbalucinogenassi = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        rbcardiacosi = new javax.swing.JRadioButton();
        rbcardiacosno = new javax.swing.JRadioButton();
        btcalcularseguro = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        labelfinal = new javax.swing.JLabel();
        terminosycondiciones = new javax.swing.JCheckBox();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("ingrese el valor base");

        jLabel2.setText("¿usted es fumador activo?");

        jLabel3.setText("¿es usted alcoholico?");

        jLabel4.setText("¿consume sustancias alucinogenas?");

        rgfumadores.add(rbfumadorsi);
        rbfumadorsi.setText("si");
        rbfumadorsi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbfumadorsiActionPerformed(evt);
            }
        });

        rgalcoholico.add(rbalcoholno);
        rbalcoholno.setText("no");

        rgfumadores.add(rbfumadorno);
        rbfumadorno.setText("no");

        rgalucinogena.add(rbalucinogenasno);
        rbalucinogenasno.setText("no");

        rgalcoholico.add(rbalcoholsi);
        rbalcoholsi.setText("si");
        rbalcoholsi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbalcoholsiActionPerformed(evt);
            }
        });

        rgalucinogena.add(rbalucinogenassi);
        rbalucinogenassi.setText("sisa valecita");

        jLabel5.setText("¿tiene antecedentes cardiacos?");

        rgcardiacos.add(rbcardiacosi);
        rbcardiacosi.setText("siiiiiiiiiiii");

        rgcardiacos.add(rbcardiacosno);
        rbcardiacosno.setText("no");

        btcalcularseguro.setText("calcular seguro de vida");
        btcalcularseguro.setEnabled(false);
        btcalcularseguro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btcalcularseguroActionPerformed(evt);
            }
        });

        jLabel6.setText("- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -");

        jLabel7.setText("- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -");

        jLabel8.setText("- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -");

        terminosycondiciones.setText("acepto terminos y condiciones ");
        terminosycondiciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                terminosycondicionesActionPerformed(evt);
            }
        });

        jLabel9.setText("- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -");

        jLabel10.setText("resultado :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(textvalorbase, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rbalucinogenassi)
                            .addComponent(jLabel4)
                            .addComponent(rbalucinogenasno)
                            .addComponent(jLabel6)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rbcardiacosno)
                            .addComponent(rbcardiacosi)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rbfumadorsi)
                                    .addComponent(rbfumadorno))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rbalcoholsi)
                                    .addComponent(rbalcoholno)
                                    .addComponent(jLabel3))
                                .addGap(26, 26, 26))
                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.CENTER, layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(144, 144, 144))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(terminosycondiciones)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(46, 46, 46)
                                .addComponent(btcalcularseguro))
                            .addComponent(jLabel8)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelfinal, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(textvalorbase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(rbalcoholsi)
                    .addComponent(rbfumadorsi))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(rbalcoholno)
                    .addComponent(rbfumadorno))
                .addGap(9, 9, 9)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbalucinogenassi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbalucinogenasno)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbcardiacosi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbcardiacosno)
                .addGap(7, 7, 7)
                .addComponent(jLabel8)
                .addGap(7, 7, 7)
                .addComponent(terminosycondiciones)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btcalcularseguro)
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(labelfinal, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(36, 36, 36))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbfumadorsiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbfumadorsiActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_rbfumadorsiActionPerformed

    private void terminosycondicionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_terminosycondicionesActionPerformed
        // TODO add your handling code here:
        if(terminosycondiciones.isSelected()){            
            btcalcularseguro.setEnabled(true);
        }else{
            btcalcularseguro.setEnabled(false);
        }
    }//GEN-LAST:event_terminosycondicionesActionPerformed

    private void rbalcoholsiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbalcoholsiActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_rbalcoholsiActionPerformed

    private void btcalcularseguroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btcalcularseguroActionPerformed
        // TODO add your handling code here:
        try {
            calcularSeguro();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "error capa 8");            
        }
        
    }//GEN-LAST:event_btcalcularseguroActionPerformed
    
    private void calcularSeguro(){
        valorBase = Long.parseLong(textvalorbase.getText());
        if(rbfumadorsi.isSelected()){
            fumador = true;
        }else{
            fumador = false;
        }if (rbalcoholsi.isSelected()){
            alcholico = true;
        }else{
            alcholico = false;
        }if (rbalucinogenassi.isSelected()){
            drogadicto = true;
        }else{
            drogadicto = false;
        }if (rbcardiacosi.isSelected()){
            cardiaco = true;
        }else{
            cardiaco = false; 
        }
        labelfinal.setText(Long.toString(calcular.calcular(valorBase, fumador, alcholico, drogadicto, cardiaco)));
            
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(seguroFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(seguroFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(seguroFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(seguroFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new seguroFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btcalcularseguro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel labelfinal;
    private javax.swing.JRadioButton rbalcoholno;
    private javax.swing.JRadioButton rbalcoholsi;
    private javax.swing.JRadioButton rbalucinogenasno;
    private javax.swing.JRadioButton rbalucinogenassi;
    private javax.swing.JRadioButton rbcardiacosi;
    private javax.swing.JRadioButton rbcardiacosno;
    private javax.swing.JRadioButton rbfumadorno;
    private javax.swing.JRadioButton rbfumadorsi;
    private javax.swing.ButtonGroup rgalcoholico;
    private javax.swing.ButtonGroup rgalucinogena;
    private javax.swing.ButtonGroup rgcardiacos;
    private javax.swing.ButtonGroup rgfumadores;
    private javax.swing.JCheckBox terminosycondiciones;
    private javax.swing.JTextField textvalorbase;
    // End of variables declaration//GEN-END:variables
}
